url: "https://outragedpinkracoon.github.io" # the base hostname & protocol for your site, e.g. http://example.com
title: "Outraged Pink Racoon" # the name of your site, e.g. ACME Corp.
locale: 'en_GB'
permalink: /:year/:month/:day/:title.html
twitter:
  username: outragedracoon
  card: summary
plugins:
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
    values:
      image:  /assets/images/site/racoon.jpg
