url: "https://www.outragedracooncoaching.com" # the base hostname & protocol for your site, e.g. http://example.com
title: "Outraged Racoon Coaching" # the name of your site, e.g. ACME Corp.
description: "Valerie Dryden — ILM certified coach based in Scotland, working remotely worldwide. No-bullshit 1:1 coaching for engineering managers and under-represented folks in tech."
author: "Valerie Dryden"
locale: 'en_GB'
permalink: /:year/:month/:day/:title.html
twitter:
  username: outragedracoon
  card: summary
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/site/racoon.jpg
      subtitle: ILM Certified Coach | Tech Exec | Neurodivergent | Queer | Non-binary | A Little Feral
  - scope:
      path: ""
      type: posts
    values:
      show_cta: true
