url: "https://www.outragedracooncoaching.com" # the base hostname & protocol for your site, e.g. http://example.com
title: "Outraged Racoon Coaching" # the name of your site, e.g. ACME Corp.
description: "Valerie Dryden — Fractional CTO and ILM certified Executive Coach based in Scotland, working remotely worldwide. No-bullshit coaching for the messy, human, hard parts of working in tech."
author: "Valerie Dryden"
locale: 'en_GB'
permalink: /:year/:month/:day/:title.html
twitter:
  username: outragedracoon
  card: summary
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/site/racoon.jpg
      subtitle: Fractional CTO | ILM Executive Coach | Neurodivergent | Queer | Chief Racoon Officer
  - scope:
      path: ""
      type: posts
    values:
      show_cta: true
